-- MySQL Script generated by MySQL Workbench
-- 02/06/16 19:35:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mtitphp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mtitphp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mtitphp` DEFAULT CHARACTER SET utf8 ;
USE `mtitphp` ;

-- -----------------------------------------------------
-- Table `mtitphp`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mtitphp`.`users` (
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NULL,
  `first_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mtitphp`.`forms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mtitphp`.`forms` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `form_title` VARCHAR(255) NULL,
  `created_time` DATETIME NULL,
  `users_email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`, `users_email`),
  INDEX `fk_forms_users_idx` (`users_email` ASC),
  CONSTRAINT `fk_forms_users`
    FOREIGN KEY (`users_email`)
    REFERENCES `mtitphp`.`users` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mtitphp`.`fields`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mtitphp`.`fields` (
  `type` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mtitphp`.`forms_fields`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mtitphp`.`forms_fields` (
  `forms_id` INT UNSIGNED NOT NULL,
  `forms_users_email` VARCHAR(255) NOT NULL,
  `fields_type` VARCHAR(255) NOT NULL,
  `field_name` VARCHAR(255) NULL,
  `order` INT UNSIGNED NULL,
  `options` VARCHAR(255) NULL,
  PRIMARY KEY (`forms_id`, `forms_users_email`, `fields_type`),
  INDEX `fk_forms_has_fields_fields1_idx` (`fields_type` ASC),
  INDEX `fk_forms_has_fields_forms1_idx` (`forms_id` ASC, `forms_users_email` ASC),
  CONSTRAINT `fk_forms_has_fields_forms1`
    FOREIGN KEY (`forms_id` , `forms_users_email`)
    REFERENCES `mtitphp`.`forms` (`id` , `users_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_forms_has_fields_fields1`
    FOREIGN KEY (`fields_type`)
    REFERENCES `mtitphp`.`fields` (`type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE `fields` ADD `name` VARCHAR(255) NOT NULL ;

INSERT INTO `fields` (`type`, `name`) VALUES
('CHEC', 'Checkbox'),
('DATE', 'Date Select Field'),
('PASS', 'Password Field'),
('RADI', 'Radio Button'),
('SUBM', 'Submit Button'),
('TEXT', 'Text Input'),
('TXTA', 'Text Area');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
